version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Install Dagger CLI
          command: cd /usr/local && { curl -L https://dl.dagger.io/dagger/install.sh | sudo sh; cd -; }
      - run:
          name: smoke tests
          command: dagger call --progress=plain -m ci ci --dir .
      - run:
          name: publish image
          command: dagger call --progress=plain -m ci publish --dir . --token env:DOCKER_TOKEN
      - run:
          name: Stop Dagger Engine
          command: docker stop -t 300 $(docker ps --filter name="dagger-engine-*" -q)